/**
 * `language_detection.feature` @AC-13 — per-turn classification and the two-consecutive-turn
 * switch (I10).
 *
 * Everything drives the real answer endpoint. The interview is parked on question 2 so the
 * ADR-I22 technical batch has already been generated by question 1's answer.
 *
 * The assertion used to be "the total `llm_calls` count did not move", which held only while
 * an answer submit made no provider call at all. Since #148 opened the K4 hook every submit
 * records two rows — the candidate pre-generation and the score — so a bare count no longer
 * says anything about the classifier. What it asserts now is the same claim, stated where it
 * cannot drift: every row the turn wrote belongs to a prompt that is *not* the classifier's.
 * `detectLanguage` compiles no prompt and has no uuid, so a row it caused could only appear
 * as one of these two — or as a third, unknown one, which is exactly what fails here.
 */
import assert from 'node:assert/strict';
import { Given, Then, When } from '@cucumber/cucumber';
import { PROMPT_NAMES, loadPromptRegistry } from '@interviewly/ai';

import { aiClient } from '../../modules/ai';
import { prisma } from '../../src/lib/db';

import { arriveAtQuestion, questionIdAt } from './answers.steps';
import { AiWorld } from './world';

/** Stop-word ratios well over `STOPWORD_MARGIN`; the below-margin one has no stop word at all. */
const TEXTS: Record<string, string> = {
  'clear Turkish stop-words':
    'Bu proje için ekiple birlikte çok daha fazla şey yaptık ve bu bir başarıydı',
  'clear English stop-words': 'I have been working with the team on this for a while now',
  'below the detection margin': 'Kubernetes Postgres Redis Docker Kafka Terraform',
};

let callsBefore = 0;
/** The interview language at the moment of the last submission — `detectLanguage`'s `current`. */
let languageBefore = '';
let classified: { language: string; ambiguous: boolean } | undefined;

/**
 * The prompts an answer submit is allowed to compile: the K4 hook's two. Resolved through the
 * registry rather than hard-coded, so a re-versioned prompt keeps its uuid and this keeps
 * working — and a *new* prompt on the answer path shows up as an unexpected row.
 */
const registry = loadPromptRegistry();
const ANSWER_PATH_PROMPT_UUIDS = new Map(
  [PROMPT_NAMES.generateCandidates, PROMPT_NAMES.scoreAnswer].map((name) => [
    registry.resolve(name).uuid,
    name,
  ]),
);

/** Fails naming the prompt, because "a row appeared" is not a diagnosis. */
async function assertNoClassificationCall(world: AiWorld): Promise<void> {
  const rows = await prisma.llmCall.findMany({
    where: { interview_id: world.interviewId },
    orderBy: { created_at: 'asc' },
    skip: callsBefore,
  });
  const unexpected = rows.filter((row) => !ANSWER_PATH_PROMPT_UUIDS.has(row.prompt_uuid));
  assert.deepEqual(
    unexpected.map((row) => row.prompt_uuid),
    [],
    'a submit recorded an llm_calls row for a prompt the answer path does not compile',
  );
}

async function submit(world: AiWorld, textKind: string): Promise<void> {
  const interview = await prisma.interview.findUniqueOrThrow({ where: { id: world.interviewId } });
  languageBefore = interview.language;
  const text = TEXTS[textKind];
  assert.ok(text, `no fixture text for "${textKind}"`);

  // The same seam the handler classifies through, so the assertions below are about the
  // client the app actually calls — and about the row it does not write.
  classified = aiClient().detectLanguage(text, languageBefore);

  await world.httpPost(`/interviews/${world.interviewId}/answers`, {
    questionId: await questionIdAt(world, interview.current_index),
    transcript: text,
    inputMode: 'text',
  });
  assert.equal(world.lastStatus, 200, `answer failed: ${JSON.stringify(world.lastBody)}`);
}

// ---------------------------------------------------------------- given

Given('an interview whose language is {string}', async function (this: AiWorld, language: string) {
  await arriveAtQuestion(this, 2, 8);
  await prisma.interview.update({ where: { id: this.interviewId }, data: { language } });
  callsBefore = await prisma.llmCall.count({ where: { interview_id: this.interviewId } });
});

// ---------------------------------------------------------------- when

When(/^I submit an answer whose text is (.+)$/, async function (this: AiWorld, textKind: string) {
  await submit(this, textKind);
});

When('I submit a clear Turkish answer', async function (this: AiWorld) {
  await submit(this, 'clear Turkish stop-words');
});

When('I submit a below-margin answer', async function (this: AiWorld) {
  await submit(this, 'below the detection margin');
});

When('I submit two consecutive clear Turkish answers', async function (this: AiWorld) {
  await submit(this, 'clear Turkish stop-words');
  await submit(this, 'clear Turkish stop-words');
});

// ---------------------------------------------------------------- then

Then(
  'no llm_calls row is recorded for the language classification',
  async function (this: AiWorld) {
    await assertNoClassificationCall(this);
  },
);

Then(
  'no llm_calls row was recorded for any language classification',
  async function (this: AiWorld) {
    await assertNoClassificationCall(this);
  },
);

Then('the classified language is {string}', function (language: string) {
  assert.equal(classified?.language, language);
});

Then('the classification ambiguous flag is {word}', function (flag: string) {
  assert.equal(classified?.ambiguous, flag === 'true');
});

/** A turn counts toward a switch exactly when the classifier was not below its margin. */
Then(/^the turn (counts|does not count) toward a language switch$/, function (counts: string) {
  assert.equal(classified?.ambiguous, counts === 'does not count');
});

Then('the interview language is still {string}', async function (this: AiWorld, language: string) {
  const interview = await prisma.interview.findUniqueOrThrow({ where: { id: this.interviewId } });
  assert.equal(interview.language, language);
});

Then('the interview language becomes {string}', async function (this: AiWorld, language: string) {
  const interview = await prisma.interview.findUniqueOrThrow({ where: { id: this.interviewId } });
  assert.equal(interview.language, language);
});
